@BookStore.Api_HostAddress = http://localhost:5006

GET {{BookStore.Api_HostAddress}}/books/
Accept: application/json

###

POST {{BookStore.Api_HostAddress}}/books/
Accept: */*
Content-Type: application/json


{
    "Id": "10",
    "Title": "The Book Thief",
    "PublishDate": "2021-01-01",
    "BasePrice": 50
}
