version: '3.8'
services:
  bookstore:
    build:
      context: .
      dockerfile: BookStore/BookStore.Api/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__BookstoreDbContext=Server=sqlserver;Database=Bookstore;User Id=bookstore;Password=bookstore;TrustServerCertificate=true
    networks:
      - skillup-network
    depends_on:
      - sqlserver
      - seq
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssw0rd
    ports:
      - "1433:1433"
    volumes:
      - type: volume
        source: data-volume
        target: /var/opt/mssql
    networks:
      - skillup-network
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5380:80"
      - "5341:5341"
    volumes:
      - type: volume
        source: logs-volume
        target: /data
    networks:
      - skillup-network
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./docker-config/prometheus:/etc/prometheus
      - prom_volume:/prometheus
    networks:
      - skillup-network
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./docker-config/grafana:/etc/grafana/provisioning/datasources
    networks:
      - skillup-network


volumes:
  data-volume:
  logs-volume:
  prom_volume:

networks:
  skillup-network:
    driver: bridge
    name: skillup-network