version: '3.8'
services:
  bookstore:
    build:
      context: .
      dockerfile: BookStore/BookStore.Api/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__BookstoreDbContext=Server=sqlserver;Database=Bookstore;User Id=bookstore;Password=bookstore;TrustServerCertificate=true
    networks:
      - skillup-network
    depends_on:
      - sqlserver
      - seq
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssw0rd
    ports:
      - "1433:1433"
    volumes:
      - type: volume
        source: data-volume
        target: /var/opt/mssql
    networks:
      - skillup-network
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5380:80"
      - "5341:5341"
    volumes:
      - type: volume
        source: logs-volume
        target: /data
    networks:
      - skillup-network

volumes:
  data-volume:
  logs-volume:

networks:
  skillup-network:
    driver: bridge
    name: skillup-network